### ISSUE TITLE
Exposing Client Secret key

### ISSUE THREAD

**Issue by WORMSS** [layervault/layervault_js_client#2]
I've just had a super quick look at your OAUTH for JS and it seems to have the 'client secret' in plain view. Do you not consider this to be a major security hole?

**Comment by meltingice** [comment]
Not really sure I understand what you mean. This is a NodeJS lib, so the OAuth credentials are always kept server-side. If you're worried about storing the client secret in the code, you can extract it to an environment variable on the server.

**Comment by WORMSS** [comment]
Ahh, ok, was looking for a way to use your API on a chrome extension. I guess its not possible then.
